route:
  group_by: ['instance', 'severity']
  group_wait: 5s
  group_interval: 10s
  repeat_interval: 1h
  receiver: alertmananger-bot

receivers:
- name: 'alertmananger-bot'
  webhook_configs:
  - send_resolved: true
    url: 'http://alertmanager-bot:8080'
