version: "3.1"
services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - 3000:3000
    networks:
      - monitoring
    volumes:
      - grafana-volume:/var/lib/grafana
  influxdb:
    image: influxdb
    container_name: influxdb
    restart: always
    ports:
      - 8086:8086
    networks:
      - monitoring
    volumes:
      - influxdb-volume:/var/lib/influxdb
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    networks:
      - monitoring
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - 9090:9090
    restart: always

  alertmanager:
    container_name: alertmanager
    image: prom/alertmanager
    ports:
      - 9093:9093
    networks:
      - monitoring
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
    restart: always

  blackbox_exporter:
    container_name: blackbox
    image: prom/blackbox-exporter
    depends_on:
      - prometheus
    dns: 8.8.8.8
    ports:
      - "9115:9115"
    networks:
      - monitoring
    volumes:
      - "./blackbox:/config"
    command:
      - '--config.file=/config/blackbox.yml'
    restart: always
  alertmanager-bot:
    container_name: alertmanager-bot
    image: metalmatze/alertmanager-bot
    environment:
      ALERTMANAGER_URL: http://alertmanager:9093
      BOLT_PATH: /data/bot.db
      STORE: bolt
      TELEGRAM_ADMIN: '8888866'
      TELEGRAM_TOKEN: 417551017:AAFTm5_SO135NJg
      TEMPLATE_PATHS: /templates/default.tmpl
      LOG_LEVEL: debug
      LISTEN_ADDR: 0.0.0.0:8080
    restart: unless-stopped
    ports:
      - 8080:8080
    networks:
      - monitoring
    depends_on:
      - alertmanager
      - prometheus
      - blackbox_exporter
    volumes:
    - ./alertmanager-bot:/data
networks:
  monitoring:
volumes:
  grafana-volume:
    external: true
  influxdb-volume:
    external: true
  prometheus_data:
    external: true

