global:
  scrape_interval: 20s # default 1 minute
  scrape_timeout: 10s

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093

rule_files:
  - rules/*.rule.yml

scrape_configs:

  - job_name: gateway_aver
    metrics_path: '/metrics'
    static_configs:
      - targets: ['192.168.105.7:9100']
  - job_name: 'ping-exporter'
    scrape_interval: 60s
    metrics_path: /probe
    params:
         prot: ['4']
    static_configs:
      - targets: 
          - 192.168.48.100
          - 192.168.48.50
          - 192.168.48.48
          - 192.168.48.10
          - 192.168.48.11
          - 192.168.48.12
          - 192.168.48.36
          - 192.168.48.15        
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
        replacement: ${1}
      - source_labels: [__param_target]
        regex: (.*)
        target_label: instance
        replacement: ${1}
      - source_labels: []
        regex: .*
        target_label: __address__
        replacement: 192.168.105.7:8085
